#ifndef MICRALN_STACKCHANNEL_UNKNOWN_CONNECTOR_H
#define MICRALN_STACKCHANNEL_UNKNOWN_CONNECTOR_H

class StackChannel_Unknown_Connector
{
public:
};

#endif //MICRALN_STACKCHANNEL_UNKNOWN_CONNECTOR_H
