#ifndef MICRALN_SIMULATIONRUNTYPE_H
#define MICRALN_SIMULATIONRUNTYPE_H

enum SimulationRunType {
    RUNNING,
    RUNNING_SLOW,
    RUNNING_VERY_SLOW,
    PAUSED,
    STEP_ONE_CLOCK,
    STEP_ONE_STATE,
    STEP_ONE_INSTRUCTION,
};


#endif //MICRALN_SIMULATIONRUNTYPE_H
