#ifndef MICRALN_SMULATIONRUNTYPE_H
#define MICRALN_SMULATIONRUNTYPE_H

enum SimulationRunType {
    RUNNING,
    PAUSED,
    STEP_ONE_FRAME,
    STEP_ONE_CLOCK,
    STEP_ONE_STATE,
    STEP_ONE_INSTRUCTION,
};


#endif //MICRALN_SMULATIONRUNTYPE_H
